config/routes.rb
FlashExpo::Application.routes.draw do
  
  namespace :admin do
    resources :developers
    resources :projects
    resources :prop_configurations
  end
  
  root to: "home#index"

end

app/models/address.rb
class Address
  include Mongoid::Document
  include Mongoid::Timestamps
  field :address1, type: String
  field :locality, type: String
  field :city, type: String
  field :zip, type: String
  field :country, type: String
  
  embedded_in :addressable, polymorphic: true
end

app/models/developer.rb
class Developer
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String
  field :logo, type: String
  field :phone, type: String
  field :email, type: String
  field :package, type: String
  
  has_many :projects, dependent: :destroy
  embeds_one :address, as: :addressable
  
  mount_uploader :logo, LogoUploader
  attr_accessible :logo, :name, :description, :phone, :email, :package, :address
  
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String
  field :status, type: String
  field :possession, type: String
  field :total_units, type: Integer
  field :sizes, type: Array
  field :total_area, type: String
  field :specifications, type: Array
  field :amenities, type: Array
  field :logo, type: String
  field :lat, type: String
  field :lng, type: String
  
  belongs_to :developer
  has_many :prop_configurations
  embeds_one :address, as: :addressable
end

app/models/prop_configuration.rb
class PropConfiguration
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :carpet, type: String
  field :saleable, type: String
  field :base_cost, type: Integer
  field :total_cost, type: Integer
  field :rate, type: Integer
  
  belongs_to :project
  belongs_to :developer
  
end

app/controllers/admin/developers_controller.rb
class Admin::DevelopersController < ApplicationController
  
  layout "admin"
  
  def index
    params[:page] ||= 1
    @developers = Developer.all.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @developer = Developer.find(params[:id])
  end

  def update
    @developer = Developer.find(params[:id])
    respond_to do |format|
      if @developer.update_attributes(params[:developer])
        flash[:success_message] = "Developer updated successfully."
        format.html { redirect_to admin_developers_path }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(params[:developer])
    respond_to do |format|
      if @developer.save
        flash[:success_message] = "Developer created successfully."
        format.html { redirect_to admin_developers_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    @developer = Developer.find(params[:id])
  end

  def destroy
    @developer = Developer.find(params[:id])
    respond_to do |format|
      if @developer.destroy
        flash[:success_message] = "Developer destroyed successfully."
        format.html { redirect_to admin_developers_path }
      else

      end
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_filter :load_developer_new, :only => [:new]
  before_filter :load_developer_create, :only => [:create]
  layout "admin"
  
  def index
    params[:page] ||= 1
    @projects = Project.all.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @project = Project.find(params[:id])
    @developer = @project.developer
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:success_message] = "Project updated successfully."
        format.html { redirect_to admin_projects_path }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def new    
    @project = @developer.projects.build
  end

  def create
    @project = @developer.projects.build(params[:project])
    respond_to do |format|
      if @project.save
        flash[:success_message] = "Project created successfully."
        format.html { redirect_to admin_projects_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.destroy
        flash[:success_message] = "Project destroyed successfully."
        format.html { redirect_to admin_projects_path }
      else
        
      end
    end
  end

  private
  def load_developer_new
    @developer = Developer.find(params[:developer])
  end
  def load_developer_create
    @developer = Developer.find(params[:project][:developer_id])
  end
end

app/controllers/admin/prop_configurations_controller.rb
class Admin::PropConfigurationsController < ApplicationController
  before_filter :load_project_new, :only => [:new]
  before_filter :load_project_create, :only => [:create]
  layout "admin"
  
  def index
    params[:page] ||= 1
    @prop_configurations = PropConfiguration.all.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @prop_configuration = PropConfiguration.find(params[:id])
    @project = @prop_configuration.project
  end

  def update
    @prop_configuration = PropConfiguration.find(params[:id])
    respond_to do |format|
      if @prop_configuration.update_attributes(params[:prop_configuration])
        flash[:success_message] = "Configuration updated successfully."
        format.html { redirect_to admin_prop_configurations_path }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def new
    @prop_configuration = PropConfiguration.new
  end

  def create
    @prop_configuration = PropConfiguration.new(params[:prop_configuration])

    respond_to do |format|
      if @prop_configuration.save
        flash[:success_message] = "Configuration created successfully."
        format.html { redirect_to admin_prop_configurations_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    @prop_configuration = PropConfiguration.find(params[:id])
  end

  # def destroy
  #   @prop_configuration = PropConfiguration.find(params[:id])
  #   respond_to do |format|
  #     if @prop_configuration.destroy
  #       flash[:success_message] = "Configuration destroyed successfully."
  #       format.html { redirect_to admin_prop_configurations_path }
  #     else

  #     end
  #   end
  # end

  private
  def load_project_new
    @project = Project.find(params[:project])
  end
  def load_project_create
    @project = Project.find(params[:prop_configuration][:project_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "admin"
  def index
  end
end

app/helpers/admin/developers_helper.rb
module Admin::DevelopersHelper
	def packages
		["Upto 1 lac", "1 lac to 2 lacs"]
	end

	def get_address1(address)
		address.address1 if address.present?
	end

	def get_city(address)
		address.city if address.present?
	end

	def get_locality(address)
		address.locality if address.present?
	end

	def get_zip(address)
		address.zip if address.present?
	end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/prop_configurations_helper.rb
module Admin::PropConfigurationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/addresses/_form.html.erb
<div class="form-group">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<%= f.label :address1, "Address" %>
			<%= f.text_field :address1, :value => get_address1(address), class: "form-control", required: "required", placeholder: "Address" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<%= f.label :city %>
			<%= f.text_field :city, :value => get_city(address), class: "form-control", required: "required", placeholder: "City" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-sm-4">
			<%= f.label :locality %>
			<%= f.text_field :locality, :value => get_locality(address), class: "form-control", required: "required", placeholder: "Locality" %>
			<%#= f.select :locality, COUNTRIES, {prompt: "Select Country", selected: "India"}, required: true, class: "form-control countries" %>
		</div>
	</div>
		
</div>
<div class="form-group">
	<div class="row">		
		<div class="col-md-4 col-sm-4">
			<%= f.label :country %>
			<%= f.select :country, COUNTRIES, {prompt: "Select Country", selected: "India"}, required: true, class: "form-control countries" %>
		</div>
		<div class="col-md-4 col-sm-4">
			<%= f.label :zip %>
			<%= f.text_field :zip, :value => get_zip(address), class: "form-control", required: "required", placeholder: "Zip" %>
		</div>
	</div>
</div>

app/views/admin/developers/_form.html.erb
<%= form_for [:admin, @developer],html: {id:"", role: "form"} do |f| %>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Developer Details</h3>
	</div> 
	
	<div class="panel-body">
		<div class="row">
			<div class="col-md-6 col-sm-12">
				<div class="form-group">
					<%= f.label :name, class: "control-label"%>
					<%= f.text_field :name, class: "form-control", tabindex: "1", required: "required" %>
				</div>
				<div class="form-group">
					<%=f.label :description, class: "control-label"%><br/>
					<%= f.text_area :description, class: "form-control", tabindex: "3", required: "required" %>
				</div>
			</div>
			<div class="col-md-6 col-sm-12">
				<div class="form-group">
					<%=f.label :phone, class: "control-label"%><br/>
					<%= f.text_field :phone, class: "form-control phone_number", tabindex: "3", required: "required" %>
				</div>
				<div class="form-group">
					<%= f.label :email, class: "control-label"%>
					<%= f.email_field :email, class: "form-control email", tabindex: "6", required: "required" %>
				</div>

				<div class="form-group">
					<%= f.label :package, class: "control-label"%>
					<%= f.select :package, packages, {:include_blank => "Please select a package"},{ class: "form-control required", tabindex: "7", required: "required"}%>					
				</div>
				<!--  -->
				<div class="form-group">
				    
					<%= f.fields_for :address do |address_form| %>
						<%= render :partial => "addresses/form", locals: {f: address_form, address: @developer.address } %>
					<% end %>
				</div>
				<!--  -->
			</div>
		</div>
	</div>
	<div class="form-group">
		<%= f.submit "Save",:class => "btn btn-primary", tabindex: "9"%>
	</div>
</div>

<% end %>

app/views/admin/developers/edit.html.erb
<div class="row">
	<h1>Edit Developer</h1>
</div>
<div class="row">
	<%= render "form" %>
</div>

app/views/admin/developers/index.html.erb
    <div class="row custyle">
		<h1 class="well">Manage Developers</h1>
    <table class="table table-striped custab">
    <thead>
        <tr>
            <th>Name</th>
            <th>Package</th>
			<th>Projects</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
        <% if @developers.count > 0 %>
		<% @developers.each do |developer| %>
            <tr>
                <td><%= developer.name %></td>
                <td><%= developer.package %></td>
				<td><%= developer.projects.count %></td>
                <td class="text-center">
                    <a class='btn btn-info btn-xs' href="<%= admin_developer_path(developer) %>"><span class="glyphicon glyphicon-edit"></span> Show</a> 
                    <a class='btn btn-info btn-xs' href="<%= edit_admin_developer_path(developer) %>"><span class="glyphicon glyphicon-edit"></span> Edit</a> 
                    <%= link_to raw("<span class='glyphicon glyphicon-remove'>Del</span>"), admin_developer_path( developer ), :method => :delete , :class => "btn btn-danger btn-xs" %>                    
                    <!-- <a class="btn btn-danger btn-xs" href="<%= edit_admin_developer_path(developer) %>"> <span class="glyphicon glyphicon-remove"></span> Del</a> -->
                </td>
            </tr>
		<% end %>
        <% else %>
            No developers found.
        <% end %>
    </table>
    </div>
	<div class="row">
		<div class="pull-left"><a class='btn btn-info btn-xs' href="<%= new_admin_developer_path %>">Add</a></div>
	<div class="pull-right">
		<%= will_paginate @developers %>
	</div>
	</div>
</div>

app/views/admin/developers/new.html.erb
<div class="row">
	<h1>Add Developer</h1>
</div>
<div class="row">
	<%= render "form" %>
</div>

app/views/admin/developers/show.html.erb
<h2> Developer Details </h2>
<td><%= @developer.name %></td>

<p><%=link_to 'Add Project', new_admin_project_path(:developer => @developer) %></p>

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project],html: {id:"", role: "form"} do |f| %>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Project Details</h3>
	</div> 
	
	<div class="panel-body">
		<div class="row">
			<div class="col-md-6 col-sm-12">				
				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control", required: "required", placeholder: "Name" %>
				</div>
				<div class="form-group">
					<%= f.label :description %>
					<%= f.text_area :description, class: "form-control", required: "required", placeholder: "Description", rows: 5 %>
				</div>
				<div class="form-group">
					<%#= f.label :possession %>
					<%#= f.text_field :possession, class: "form-control datepicker", required: "required", placeholder: "Possession", readonly: "readonly", data: {:"date-format" => "dd/mm/yyyy"} %>
				</div>
				<div class="form-group">
					<%= f.label :lat, "Exact location" %>
					<div class="row">
						<div class="col-xs-6">
							<%= f.text_field :lat, class: "form-control", required: "required", placeholder: "Latitude" %>
						</div>
						<div class="col-xs-6">
							<%= f.text_field :lng, class: "form-control", required: "required", placeholder: "Longitude" %>
						</div>
					</div>
				</div>

			</div>

			<div class="col-md-6 col-sm-12">				
				<div class="form-group">
					<%=f.label :total_units, class: "control-label"%><br/>
					<%= f.text_field :total_units, class: "form-control ", tabindex: "3", required: "required" %>
				</div>
				<div class="form-group">
					<%=f.label :total_area, class: "control-label"%><br/>
					<%= f.text_field :total_area, class: "form-control ", tabindex: "3", required: "required" %>
				</div>
				<div class="form-group">
					<%# @project.address ||= @project.build_address %>			    
					<%= f.fields_for :address do |address_form| %>
						<%= render :partial => "addresses/form", locals: {f: address_form, address: @project.address } %>
					<% end %>
				</div>
			</div>
			<%= f.hidden_field :developer_id,:value => @developer.id ,class: "form-control required"%>
			<div class="form-group">
				<%= f.submit "Save",:class => "btn btn-primary", tabindex: "9"%>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="row">
	<h1 class="well">Edit Project</h1>
</div>
<div class="row">
	<%= render "form" %>
</div>

app/views/admin/projects/index.html.erb
    <div class="row custyle">
		<h1 class="well">Manage Projects</h1>
    <table class="table table-striped custab">
    <thead>
        <tr>
            <th>Name</th>
            <th>Developer</th>
			<th>Location</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
        <% if @projects.count > 0 %>
		<% @projects.each do |project| %>
            <tr>
                <td><%= project.name %></td>
                <td><%= project.developer.name %></td>
				<td><%= "#{project.address.locality}, #{project.address.city}" %></td>
                <td class="text-center">
                    <a class='btn btn-info btn-xs' href="<%= admin_project_path(project) %>"><span class="glyphicon glyphicon-edit"></span> Show</a> 
                    <a class='btn btn-info btn-xs' href="<%= edit_admin_project_path(project) %>"><span class="glyphicon glyphicon-edit"></span> Edit</a> 
                    <%= link_to raw("<span class='glyphicon glyphicon-remove'>Del</span>"), admin_project_path( project ), :method => :delete , :class => "btn btn-danger btn-xs" %>                    
                    <!-- <a class="btn btn-danger btn-xs" href="<%#= admin_project_path(project) %>" method='delete'><span class="glyphicon glyphicon-remove"></span> Del</a></td> -->
            </tr>
		<% end %>
        <% else %>
            No projects found.
        <% end %>
        
    </table>
    </div>
	<div class="row">
		<!-- <div class="pull-left"><a class='btn btn-info btn-xs' href="<%= new_admin_project_path %>">Add</a></div> -->
	<div class="pull-right">
		<%= will_paginate @projects %>
	</div>
	</div>
</div>

app/views/admin/projects/new.html.erb
<div class="row">
	<h1 class="well">Add Project</h1>
</div>
<div class="row">
	<%= render "form" %>
</div>

app/views/admin/projects/show.html.erb
<h2> Project Details </h2>
<td><%= @project.name %></td>

<p><%=link_to 'Add Configuration', new_admin_prop_configuration_path(:project => @project) %></p>

app/views/admin/prop_configurations/_form.html.erb
<%= form_for [:admin, @prop_configuration],html: {id:"", role: "form"} do |f| %>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Configuration Details</h3>
	</div> 
	
	<div class="panel-body">
		<div class="row">
			<div class="col-md-6 col-sm-12">				
				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control", required: "required", placeholder: "Name" %>
				</div>
				<div class="form-group">
					<%= f.label :carpet %>
					<%= f.text_field :carpet, class: "form-control", required: "required", placeholder: "Carpet", rows: 5 %>
				</div>

			</div>

			<div class="col-md-6 col-sm-12">				
				<div class="form-group">
					<%=f.label :base_cost, class: "control-label"%><br/>
					<%= f.text_field :base_cost, class: "form-control ", tabindex: "3", required: "required" %>
				</div>
				<div class="form-group">
					<%=f.label :total_cost, class: "control-label"%><br/>
					<%= f.text_field :total_cost, class: "form-control ", tabindex: "3", required: "required" %>
				</div>
				<div class="form-group">
					<%=f.label :rate, class: "control-label"%><br/>
					<%= f.text_field :rate, class: "form-control ", tabindex: "3", required: "required" %>
				</div>
			</div>
			<%= f.hidden_field :project_id,:value => @project.id ,class: "form-control required"%>
			<div class="form-group">
				<%= f.submit "Save",:class => "btn btn-primary", tabindex: "9"%>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/admin/prop_configurations/edit.html.erb
<div class="row">
	<h1 class="well">Edit Configurations</h1>
</div>
<div class="row">
	<%= render "form" %>
</div>

app/views/admin/prop_configurations/index.html.erb
    <div class="row custyle">
		<h1 class="well">Manage Configurations</h1>
    <table class="table table-striped custab">
    <thead>
        <tr>
            <th>Name</th>
            <th>Project</th>
			<th>Total Cost</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
        <% if @prop_configurations.count > 0 %>
		<% @prop_configurations.each do |config| %>
            <tr>
                <td><%= config.name %></td>
                <td><%= config.project.name %></td>
                <td><%= config.total_cost %></td>				
                <td class="text-center">
                    <a class='btn btn-info btn-xs' href="<%= edit_admin_prop_configuration_path(config) %>"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                    <%#= link_to raw("<span class='glyphicon glyphicon-remove'>Del</span>"), admin_prop_configurations_path( config ), :method => :delete , :class => "btn btn-danger btn-xs" %>                    
                   
                </td>
            </tr>
		<% end %>
        <% else %>
            No Configurations Present.
        <% end %>
        
    </table>
    </div>
	<div class="row">
		<!-- <div class="pull-left"><a class='btn btn-info btn-xs' href="<%#= new_admin_prop_configuration_path %>">Add</a></div> -->
    	<div class="pull-right">
    		<%= will_paginate @prop_configurations %>
    	</div>
	</div>
</div>

app/views/admin/prop_configurations/new.html.erb
<div class="row">
	<h1 class="well">Add Configuration</h1>
</div>
<div class="row">
	<%= render "form" %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p><%=link_to 'Add Developer', new_admin_developer_path %></p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashExpo</title>
  <%= stylesheet_link_tag    "admin", :media => "all" %>
  <%= javascript_include_tag "admin" %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<div class="nav-side-menu">
	    <div class="brand">Delhi Realty Expo</div>
	    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
	        <div class="menu-list">
  
	            <ul id="menu-content" class="menu-content collapse out">
	                <li>
	                  <a href="#">
	                  <i class="fa fa-dashboard fa-lg"></i> Dashboard
	                  </a>
	                </li>

	                <li  data-toggle="collapse" data-target="#products" class="collapsed active">
	                  <a href="<%= admin_developers_path %>"><i class="fa fa-gift fa-lg"></i> Developers <span class="arrow"></span></a>
	                </li>
	                <ul class="sub-menu collapse" id="products">
	                    <li class="active"><a href="#">Search Form</a></li>
	                    
	                </ul>


	                <li data-toggle="collapse" data-target="#service" class="collapsed">
	                  <a href="<%= admin_projects_path %>"><i class="fa fa-globe fa-lg"></i> Projects <span class="arrow"></span></a>
	                </li>  
	                <ul class="sub-menu collapse" id="service">
	                  <li>Search Form</li>
	                </ul>

	                <li  data-toggle="collapse" data-target="#products" class="collapsed">
	                  <a href="<%= admin_prop_configurations_path %>"><i class="fa fa-gift fa-lg"></i> configurations <span class="arrow"></span></a>
	                </li>

					<li>
						<a href="#">
						<i class="fa fa-user fa-lg"></i> Offers
						</a>
					</li>

					<li>
						<a href="#">
						<i class="fa fa-users fa-lg"></i> Leads
						</a>
					</li>
	            </ul>
	     </div>
	</div>
	<div class="col-md-9 col-md-offset-3">
<%= yield %>
	</div>
</div>
</body>
</html>